#ifndef SGUI_COLORS_H
#define SGUI_COLORS_H



#define SGUI_WINDOW_COLOR        0x646464
#define SGUI_INSET_FILL_COLOR_L1 0x323232
#define SGUI_INSET_FILL_COLOR_L2 0x161616

#define SGUI_OUTSET_COLOR        0xFFFFFF
#define SGUI_INSET_COLOR         0x000000

#define SGUI_CHECKBOX_TICK_COLOR 0xFFFFFF

#define SGUI_RADIO_BUTTON_COLOR  0xFFFFFF

#define SGUI_PROGRESS_BAR_COLOR  0xFFFFFF

#define SGUI_FOCUS_BOX_COLOR     0xFFA500

#define SGUI_DEFAULT_TEXT        0xFFFFFF



#endif /* SGUI_COLORS_H */

