#ifndef SGUI_COLORS_H
#define SGUI_COLORS_H



#define SGUI_YELLOW       0xFFFF00
#define SGUI_WHITE        0xFFFFFF
#define SGUI_BLACK        0x000000
#define SGUI_GRAY         0x646464
#define SGUI_GRAY_HALF    0x323232
#define SGUI_GRAY_QUARTER 0x161616


#define SGUI_WINDOW_COLOR        SGUI_GRAY
#define SGUI_INSET_FILL_COLOR_L1 SGUI_GRAY_HALF
#define SGUI_INSET_FILL_COLOR_L2 SGUI_GRAY_QUARTER

#define SGUI_OUTSET_COLOR        SGUI_WHITE
#define SGUI_INSET_COLOR         SGUI_BLACK

#define SGUI_CHECKBOX_TICK_COLOR SGUI_WHITE
#define SGUI_RADIO_BUTTON_COLOR  SGUI_WHITE



#endif /* SGUI_COLORS_H */

