set( CMAKE_SYSTEM_NAME Windows )

set( CMAKE_C_COMPILER i486-mingw32-gcc )
set( CMAKE_RC_COMPILER i486-mingw32-windres )
set( CMAKE_AR i486-mingw32-ar )
set( CMAKE_RANLIB i486-mingw32-ranlib )

set( CMAKE_FIND_ROOT_PATH /usr/i486-mingw32 )

set( CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER )
set( CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY )
set( CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY )
